### PR TITLE
Adding LM Studio Support

### PR DESCRIPTION
**Pull request by ayoubachak**
Added the option to use local models via LM Studio, which gave decent results, here is an example of me asking mistral instruct 7B to make the game of life :

image

Note : I've set the context size to 32768 tokens even though most of them were not used, but I had some issue using other models like gemma 7b where it kept looping through the prompt infinitly.

### CODE REVIEW

**Comment by Ascendant-Stoic** [comment]
I downloaded the files you edited and copied them to their corresponding Devika folders and activated LM Studio local server but I still can't get it to work ... I even edited the Config.toml and added an this line --> LM_STUDIO = "http://localhost:1234/v1/chat/completions" to be able to edit LM_Studio API Endpoint in the settings and still nothing, what am I doing wrong?

**Comment by elegos** [comment]
Besides the `package-lock.json` file addition, which I think it should not be added in this PR, the feature works, or at least Devika is able to connect to LM Studio. Still fighting against model outputting proper format, but that's another issue.

**Comment by ARajgor** [comment]
Package lock file should be removed.

**Comment by ayoubachak** [comment]
> Package lock file should be removed.

Done !

**Pull request merged**
