### PR TITLE
Added logging to all routes

### LINKED ISSUE #5: Implement extensive logging throughout the project
The [`Logger`](https://github.com/stitionai/devika/blob/main/src/logger.py) has not been integrated into the project yet. All agent routes and code paths should implement extensive logging.

### PR DESCRIPTION
**Pull request by rohittp0**
This pull request primarily involves updates to the logging system in the `devika.py` and `src/logger.py` files. The changes include the introduction of a `route_logger` decorator for logging route entry and exit points, and the adjustment of logger instantiation in `devika.py`. A minor change was also made to the `.gitignore` file in the `ui` folder.

## Logging system updates:

* [`devika.py`](diffhunk://#diff-6197fd0ad9004284b414c00f8881514ffa041a569641a338c5d1dec4546f2c51L12-R12): The `Logger` instantiation was moved to the start of the file and all routes were decorated with `@route_logger(logger)`, which logs the entry and exit points of each route. The booting up log message was also moved to the end of the file.

* [`src/logger.py`](diffhunk://#diff-cf7075f01196f97260daf989b9b49230b3812683987ca3dda215408a36827545R1-R4): A `route_logger` decorator was added. This decorator logs the entry and exit points of routes, including a summary of the response if possible. 

## Minor updates:

Added `pnpm-lock.yaml` and `.idea` to the list of ignored files.

## Closes

#5 - Implement extensive logging throughout the project

### CODE REVIEW

**Comment by rohittp0** [comment]
@123vivekr Can you review this PR? If this is ok I can move on to adding logging to more of the code paths. Please let me know if there is anything to be changed 😄

**Comment by 123vivekr** [comment]
Thanks for the great code :) Merging right away

**Comment by 123vivekr** [comment]
> If this is ok I can move on to adding logging to more of the code paths
Yes please!
Let me know if you need any help :D

**Comment by NinjaEde** [comment]
@rohittp0 How can I set the Log-Level? I get spamed on my console with INFO and DEBUG log statements every second

**Pull request merged**
