### PR TITLE
added web interface, gemini 1.0, 1.5, duckduckgo, google search api, bun install in setup.sh

### PR DESCRIPTION
**Pull request by nalaso**
**This pull request makes the following changes.**
 
- Added gemini 1.0, 1.5 support
- Added duckduckgo web search support
- changed npm install to bun install in setup.sh

Solved the following issue
#97 #65 #71 #35 #6 

**second commit**
- Added support for **google search api**
- Corrected **set_gemini_api_key**

Solved the following issue
#90 #38 

Edit new

Also  made the following changes.

- Added support for web_search interface  

1. to change web_search value using config file
change WEB_SEARCH in config.toml 
accepted values - google|bing|ddgs

2. to change web_search value using cmd
`python devika.py --websearch <type>`
replace <type> with google|bing|ddgs

`python devika.py` uses ddgs as default

3. to change web_search value using api request
in /api/execute-agent
pass web_search along with other data

- Also corrected the error caused while using ollama local models

changed "ollama" to "client" in inference function

### CODE REVIEW

**Comment by sumit171204** [comment]
Gemini Working 👍

**Comment by MaksymSofer** [comment]
Does system check presence of at least one api-key for DuckDuckGO \ Bing \ Google?
would be good to have some system message in console " api key for X found, search via X will be used"

**Comment by sumit171204** [comment]
System does not check for any one api, you have to select the model , it
will be good to have a console message so we can check if the api keys are
working properly or not.

**Comment by Ahmet0691** [comment]
thanks u, it is working

**Comment by Ahmet0691** [comment]
Is duckduckgo working?

**Comment by AlTarV** [comment]
Devika won't start - what could be the problem? 

24.03.28 20:13:01: root: INFO   : /api/token-usage GET
24.03.28 20:13:01: root: DEBUG  : /api/token-usage GET - Response: {
  "token_usage": 0
}

24.03.28 20:13:01: root: INFO   : /api/project-list GET
24.03.28 20:13:01: root: DEBUG  : /api/project-list GET - Response: {
  "projects": [
    "Test01",
    "Test02"
  ]
}

24.03.28 20:13:01: root: INFO   : /api/model-list GET
24.03.28 20:13:01: root: DEBUG  : /api/model-list GET - Response: {
  "models": [
    [
      "Claude 3 Opus",
      "claude-3-opus-20240229"
    ],
    [
      "Claude 3 Sonnet",
      "claude-3-sonnet-20240229"
    ],
    [
      "Claude 3 Haiku",
      "claude-3-haiku-20240307"
    ],
    [
      "GPT-4 Turbo",
      "gpt-4-0125-preview"
    ],
    [
      "GPT-3.5",
      "gpt-3.5-turbo-0125"
    ],
    [
      "Gemini 1.0 Pro",
      "gemini-1.0-pro"
    ],
    [
      "Gemini 1.5 Pro",
      "gemini-1.5-pro"
    ]
  ]
}

24.03.28 20:13:01: root: INFO   : /api/get-agent-state POST
24.03.28 20:13:01: root: DEBUG  : /api/get-agent-state POST - Response: {
  "state": null
}

24.03.28 20:13:01: root: INFO   : /api/get-messages POST
24.03.28 20:13:01: root: DEBUG  : /api/get-messages POST - Response: {
  "messages": [
    {
      "from_devika": false,
      "message": "\u0447\u0435\u043c \u043c\u043e\u0436\u0435\u0448\u044c \u043f\u043e\u043c\u043e\u0447\u044c ",
      "timestamp": "2024-03-28 20:04:37"
    },
    {
      "from_devika": false,
      "message": "\u0447\u0435\u043c \u043c\u043e\u0436\u0435\u0448\u044c \u043f\u043e\u043c\u043e\u0447\u044c",
      "timestamp": "2024-03-28 20:11:47"
    }
  ]
}

**Comment by AlTarV** [comment]
I'm new to Github - if I asked the wrong question - I apologize in advance.

**Comment by Ahmet0691** [comment]
can u come to discord channel of devika

**Comment by TaylorBechard** [comment]
Would love to see duckduckgo working as well! Looking forward to when this is verified and merged in 🙏

**Comment by nalaso** [comment]
closing this further discussion will be done in #246

**Comment by nalaso** [comment]
New edit

Also makes the following changes.

Added support for web_search interface
to change web_search value using config file
change WEB_SEARCH in config.toml
accepted values - google|bing|ddgs

to change web_search value using cmd
python devika.py --websearch <type>
replace with google|bing|ddgs

python devika.py uses ddgs as default

to change web_search value using api request
in /api/execute-agent
pass web_search along with other data
Also corrected the error caused while using ollama local models
changed "ollama" to "client" in inference function

**Comment by mufeedvh** [comment]
Thank you so much, I am merging this now! 🙌 ❤️

**Comment by PierrunoYT** [comment]
> can u come to discord channel of devika

DM me on Discord @Ahmet0691

**Comment by nullnuller** [comment]
Hi,
Why is there no Gemini 1.5 pro available, only 1.0 ?
image

**Pull request merged**
