### PR TITLE
Update researcher.py

### PR DESCRIPTION
**Pull request by Abhishekrajpurohit**
there is a 
Unsupported operand type s for |: type and type 
error, ive done a few changes

### CODE REVIEW

**Comment by jmtatsch** [comment]
The problem was just that python < 3.10 is incompatible with new typing syntax.
Not sure if all type hints should be rewritten in a compatible manner or if the project should just require python >= 3.10 which is quite reasonable in 2024.

**Comment by Abhishekrajpurohit** [comment]
On a MacOS MacBook M1
Even with a Python version 3.12. the error still persisted

**Comment by jmtatsch** [comment]
That is impossible. Maybe your venv uses an older python version?
How did you install python 3.12? brew?

**Comment by ARajgor** [comment]
copy of https://github.com/stitionai/devika/pull/345

we recommand to use >= 3.10 and < 3.12. I tested it with that not an issue. currently, so many projects doesn't support 3.12

**Pull request closed without merging**
