### PR TITLE
New UI

### PR DESCRIPTION
**Pull request by nalaso**
Pr for new UI

Based on the discussion in new theme thread under frontend.
Suggestions are welcomed there.

Development is based on kartik's design

- [x] new ui 

1. Home page 
- [x] color indicator for selected route in sidebar
- [ ] temperature of model 
- [ ] code editor/viewer
- [x] fully scrollable browser page 

2. Settings page
- [x] setting for dark/light theme switch
- [ ] max token configuration
- [ ] default model configuration
- [ ] default search engine configuration

4. Log page
- [ ] filter by time
- [ ] log type preferences like route log and prompt logs

current state edit 4

[converted.webm](https://github.com/stitionai/devika/assets/73838186/9ff3cdde-04c9-4897-8d7e-8909fefd8da8)

Screenshot 2024-04-05 at 8 05 41 PM
Screenshot 2024-04-05 at 8 05 08 PM
Screenshot 2024-04-05 at 8 05 21 PM

### CODE REVIEW

**Comment by franklinselva** [comment]
@nalaso That’s a nice addition

**Comment by Guerdal** [comment]
I try your modifications in ui with paste ui directory in place of ui of devika sources.
I build the dockers and voila!! all functions.
Great work :-)

**Comment by KenAijmNight** [comment]
I think it is smart to make a small task list on what must still be done and keep track of it in the fork/pull request that you have here. 

- [ ] Needs to be done?

**Comment by Ahmet0691** [comment]
will there be switching between themes

**Comment by kartikk-k** [comment]
> will there be switching between themes

yes, we will have dark and light mode initially but you can expect multi-theme

**Comment by nalaso** [comment]
should we move search engine selection to drawar?

**Comment by Ahmet0691** [comment]
monologue closes the chat, not a convenient interface, thema is good but the locations are not suitable

**Comment by kartikk-k** [comment]
> monologue closes the chat, not a convenient interface, thema is good but the locations are not suitable

What you said is a valid point but we are constantly working on improving the UI as well as the UX so, we will try to give the option to pin/unpin like the previous UI or find something that solves this problem

**Comment by nalaso** [comment]
> monologue closes the chat, not a convenient interface, thema is good but the locations are not suitable

[converted.webm](https://github.com/stitionai/devika/assets/73838186/478fdca6-e9e6-46bd-bc72-2bd971035e2b)

**Pull request merged**
