### PR TITLE
Update devika.py

### PR DESCRIPTION
**Pull request by ImSuvodeep**
this executes the provided Python code string using the exec() function. It captures any output or result from the execution and returns an appropriate message in the JSON response...

### CODE REVIEW

**Comment by darrassi1** [comment]
agent run work 2 time , one by one , wich cause sub process issue

**Comment by ImSuvodeep** [comment]
Ok let me fix that

**Comment by ImSuvodeep** [comment]
> agent run work 2 time , one by one , wich cause sub process issue

maybe i have solved the issue that u have earlier ..could you mind to check it out??

**Comment by ARajgor** [comment]
fetch the latest commits it's working

**Comment by ImSuvodeep** [comment]
> fetch the latest commits it's working

so may in know why you haven't merged it with the main brunch??

**Pull request closed without merging**
