### PR TITLE
Fixed Bugs and Added some useful functions..

### PR DESCRIPTION
**Pull request by Rawknee-69**
Fixed Bugs and Added some useful functions..

### CODE REVIEW

**Comment by darrassi1** [comment]
its producing endless loop of invalid response  action ::  answer

24.04.24 15:47:18: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 2652}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:22: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 1998}
Invalid response from the model, trying again...
24.04.24 15:47:22: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 3714}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:28: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 3200}
Invalid response from the model, trying again...
24.04.24 15:47:28: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 4846}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:33: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 4240}
Invalid response from the model, trying again...
24.04.24 15:47:33: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 5932}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:36: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 5128}
Invalid response from the model, trying again...
24.04.24 15:47:36: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 6919}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:40: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 6233}
Invalid response from the model, trying again...
24.04.24 15:47:40: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 7965}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:45: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 7331}
Invalid response from the model, trying again...
24.04.24 15:47:45: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 9037}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:49: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 8375}
Invalid response from the model, trying again...
24.04.24 15:47:49: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 10095}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:55: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 9621}
Invalid response from the model, trying again...
24.04.24 15:47:55: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 11247}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:47:59: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 10531}
Invalid response from the model, trying again...
24.04.24 15:47:59: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 12278}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:03: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 11682}
Invalid response from the model, trying again...
24.04.24 15:48:03: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 13369}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:07: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 12615}
Invalid response from the model, trying again...
24.04.24 15:48:07: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 14381}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:10: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 13557}
Invalid response from the model, trying again...
24.04.24 15:48:10: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 15358}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:16: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 14912}
Invalid response from the model, trying again...
24.04.24 15:48:16: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 16524}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:19: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 15710}
Invalid response from the model, trying again...
24.04.24 15:48:19: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 17506}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:23: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 16784}
Invalid response from the model, trying again...
24.04.24 15:48:23: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 18534}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:29: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 18128}
Invalid response from the model, trying again...
24.04.24 15:48:29: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 19720}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:32: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 18902}
Invalid response from the model, trying again...
24.04.24 15:48:32: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 20700}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:37: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 20042}
Invalid response from the model, trying again...
24.04.24 15:48:37: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 21760}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:42: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 21226}
Invalid response from the model, trying again...
24.04.24 15:48:42: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 22882}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:46: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 22200}
Invalid response from the model, trying again...
24.04.24 15:48:46: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 23930}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:51: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 23308}
Invalid response from the model, trying again...
24.04.24 15:48:51: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 25008}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:48:59: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 24720}
Invalid response from the model, trying again...
24.04.24 15:48:59: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 26253}
Model: gemini-pro, Enum: GOOGLE
24.04.24 15:49:03: root: INFO   : SOCKET tokens MESSAGE: {'token_usage': 25619}

**Comment by darrassi1** [comment]
try making small PR

**Comment by Rawknee-69** [comment]
Bro try restarting the project server and make a new project and then try it and to be specific which model are you using...

**Comment by ARajgor** [comment]
Can you remove ui files from here. Just keep rag faiss and improved promptes.

We create help section in a different pr.

**Pull request closed without merging**
