### PR TITLE
Enhance Bug Report Template

### PR DESCRIPTION
**Pull request by MrAnayDongre**
This pull request aims to enhance the Bug Report template by adding two new sections:

1. **Prompt**: This section allows users to specify the prompt or input they provided to the system when encountering the bug.

2. **Environment and Tools**: This section helps gather information about the Large Language Model (LLM) and search engine used in the environment where the bug occurred. This is crucial for identifying potential compatibility issues or dependencies related to specific tools or services.

### CODE REVIEW

**Comment by ARajgor** [comment]
Merge this,

```
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**NOTE**: Your issue may already be reported! Please search on the [issue tracker](https://github.com/stitionai/devika/issues) before creating one.



### Describe the bug 
A clear and concise description of what the bug is.

### To Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

### Expected behavior
A clear and concise description of what you expected to happen.

### Screenshots
must share logs from frontend or backend or If applicable, add screenshots to help explain your problem. 

### setup
- OS: [e.g. Windows, Linux, MacOS]
- Python version: [e.g. 3.10]
- Node version: [e.g. 18.0.0]
- bun version: [e.g. 0.1.0]

#### Additional context
Add any other context about the problem here.

```

**Comment by MrAnayDongre** [comment]
Wouldn't specifying the LLM and the search-engine used lead to more accurate debugging? Since, a tool specific issue/error might occur.

**Comment by ARajgor** [comment]
> Wouldn't specifying the LLM and the search-engine used lead to more accurate debugging? Since, a tool specific issue/error might occur. 

That's why I said merge not replace

**Comment by ARajgor** [comment]
https://github.com/stitionai/devika/pull/387

**Pull request closed without merging**
