### PR TITLE
Add precommit configurations & basic GitHub actions

### LINKED ISSUE #153: Add pre-commit configurations and basic GitHub actions to validate the changes effortlessly
Now might be a good time to start adding dev configurations to the project. We can start considering pre-commit configurations to keep everyone's changes in self-check effortlessly. Also, adding a basic checker to Github actions before reviewing the code would save us more time in a longer run.

If this proposal is okay, I am willing to take it up myself.

### PR DESCRIPTION
**Pull request by franklinselva**
Resolves #153

### CODE REVIEW

**Comment by franklinselva** [comment]
The PR cannot be merged at this point yet since it has a lot of expected formatting and linting changes. The details are available at this [job](https://github.com/franklinselva/devika/actions/runs/8447522972).

I will update the install scripts for normal setup and dev setup soon.

**Comment by mufeedvh** [comment]
Hey @franklinselva, please let me know when you want this to be merged, the PR looks okay to me so far! Thanks! 🙌

**Comment by franklinselva** [comment]
@mufeedvh I think waiting until #24 is merged is better since this PR will add more conflicts. But I would like you to look over the current changes before adding any formatting and linting-related commits.

**Comment by franklinselva** [comment]
@mufeedvh I think we can go ahead with merging this PR. Can you go through the changes? This [commit](https://github.com/stitionai/devika/pull/181/commits/5b25507ab906843bc88b44d6a196981461586ff7) is strictly formatting related changes. The linting part is being improved as a part of refactoring

**Pull request closed without merging**
