### PR TITLE
Update knowledge_base.py

### PR DESCRIPTION
**Pull request by ImSuvodeep**
Implemented BM25 search functionality for knowledge retrieval in KnowledgeBase class

### CODE REVIEW

**Comment by juvi21** [comment]
Looks good to me. It would be cool if you could add the BM25Okapi package to the '**requirements.txt**'

**Comment by ImSuvodeep** [comment]
Done

**Comment by juvi21** [comment]
Commit the updated requirements.txt to this pull request instead of opening a new one. I think you can close https://github.com/stitionai/devika/pull/254 :)

**Comment by darrassi1** [comment]
Exception in thread Thread-11:
Traceback (most recent call last):
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 973, in _bootstrap_inner
    self.run()
  File "C:\Users\pc\AppData\Local\Programs\Python\Python39\lib\threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pc\Desktop\fork\devika\devika.py", line 97, in <lambda>
    thread = Thread(target=lambda: agent.execute(message, project_name))
  File "C:\Users\pc\Desktop\fork\devika\src\agents\agent.py", line 353, in execute
    search_results = self.search_queries(queries, project_name)
  File "C:\Users\pc\Desktop\fork\devika\src\agents\agent.py", line 72, in search_queries
    knowledge_base = KnowledgeBase()
  File "C:\Users\pc\Desktop\fork\devika\src\memory\knowledge_base.py", line 31, in __init__
    self.bm25 = BM25Okapi(self.tokenized_contents)
  File "C:\Users\pc\Desktop\devika\.venv\lib\site-packages\rank_bm25.py", line 83, in __init__
    super().__init__(corpus, tokenizer)
  File "C:\Users\pc\Desktop\devika\.venv\lib\site-packages\rank_bm25.py", line 27, in __init__
    nd = self._initialize(corpus)
  File "C:\Users\pc\Desktop\devika\.venv\lib\site-packages\rank_bm25.py", line 52, in _initialize
    self.avgdl = num_doc / self.corpus_size
ZeroDivisionError: division by zero

``

**Comment by ImSuvodeep** [comment]
let me know if the new commit fix ur error

**Comment by darrassi1** [comment]
> let me know if the new commit fix ur error

the error is gone

**Comment by ARajgor** [comment]
Need testing

**Comment by ARajgor** [comment]
Also add it to requirements

**Pull request closed without merging**
