### PR TITLE
Fixed open ai windows api key issue and related issue

### LINKED ISSUE #59: Openai api ket not working
TypeError: OpenAI.__init__() missing 1 required positional argument: 'api_key'
[2024-03-22 13:20:25,809] ERROR in app: Exception on /api/project-list [GET]
Traceback (most recent call last):

### LINKED ISSUE #61: Error on Bun run dev
I cd to the ui folder and bun run dev but I receive the following error message:

$ vite
file:///mnt/Essam/AI/devika/ui/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
error: script "dev" exited with code 1

### PR DESCRIPTION
**Pull request by titonova**
Closes #59 

Signed-off-by: titonova 41286822+titonova@users.noreply.github.com

### CODE REVIEW

**Comment by 123vivekr** [comment]
Hey thanks for the fix, there was already a PR for this from another contributor - can you check the `main` branch if it works and add anything you think is missing?

**Comment by titonova** [comment]
@123vivekr They didn't fix the open ai key issue just the conflicting class names

**Comment by Israel-Laguan** [comment]
@titonova try to rebase your PR

**Comment by titonova** [comment]
> rebase your PR

@Israel-Laguan No point, I dont think it's going to be accepted regardless

**Pull request closed without merging**
