### PR TITLE
Error during model inference: name 'ollama' is not defined

### PR DESCRIPTION
**Pull request by daliborkrejic**

### CODE REVIEW

**Review by rajakumar05032000 — COMMENTED** [review]
Already these changes are implemented in PR #215

**Comment by rajakumar05032000** [comment]
> Already these changes are implemented in the earlier PR #215, its about to get merged.

**Comment by hqnicolas** [comment]
devika-backend-engine-1:
root: ERROR  : Error during model inference: name 'ollama' is not defined

 with external ollama server and using the internal ollama server on docker compose

**Comment by ARajgor** [comment]
#24

**Pull request closed without merging**
