### PR TITLE
Integrate Decision agent and Implement action logic

### PR DESCRIPTION
**Pull request by yryuvraj**
A humble try to handle #1 

This commit integrates the Decision agent into the agent execution flow in `src/agents/agent.py`. It adds logic to perform actions based on the decisions made by the Decision agent.

Please review properly before closing or merging. New to Open Source Dev. 

Thanks!

### CODE REVIEW

**Comment by Ahmet0691** [comment]
did u check it pip install os ?

**Comment by yryuvraj** [comment]
@Ahmet0691 What do you mean? Can you please elaborate

**Comment by Ahmet0691** [comment]
there is an error in adding and editing code, some code seems to be rewritten without deleting it when it already exists. pip install os is not installed

**Comment by yryuvraj** [comment]
I have added os in the `requirements.txt`

And as for the other part, I cannot find anything rewritten by me. But please do let me know if you find any discrepancy.

**Comment by mufeedvh** [comment]
You should be using helper functions like: https://github.com/stitionai/devika/blob/main/src/services/git.py for all actions, since all of them has already been implemented, just not integrated yet. Thanks for the PR!

**Comment by yryuvraj** [comment]
Hey @mufeedvh I think I now know where I went wrong. Will create a new Pull Request using the helper functions (or) services.

Thanks for reviewing and responding!

**Pull request closed without merging**
